### PR TITLE
fix a typo in the example of SIR

### PR DESCRIPTION
**Pull request by gxcuit**
Signed-off-by: gxcuit gxcuit@163.com 
Fixes  ISSUE #3743

Changes:

1. Fix a Bug/typo in the example of SIR: swap the reader(data input) of the guest and the host.

2.

3.

### CODE REVIEW

**Comment by dylan-fan** [comment]
https://github.com/FederatedAI/FATE/issues/3832

**Comment by nemirorox** [comment]
Hi,  this config file is to demonstrate server(guest) securely retrieves value from client(host). Use of datasets do not have to be restricted here as for other modules. Here we keep the choice of data sets consistent with the [earliest version](https://github.com/FederatedAI/FATE/blob/v1.5.0/examples/dsl/v1/secure_information_retrieval/test_secure_information_retrieval_conf.json).  
Therefore, we will not merge this PR as the current example works.

**Comment by gxcuit** [comment]
> Hi, this config file is to demonstrate server(guest) securely retrieves value from client(host). Use of datasets do not have to be restricted here as for other modules. Here we keep the choice of data sets consistent with the [earliest version](https://github.com/FederatedAI/FATE/blob/v1.5.0/examples/dsl/v1/secure_information_retrieval/test_secure_information_retrieval_conf.json). Therefore, we will not merge this PR as the current example works.

Hi, thanks for your reply! I still have questions. 

I know it is the guest who wants to retrieve data from the host.  But, In the original conf file, the `reader_0` of the guest is set to `breast_hetero_host`. **This means that the guest's input is the host's data.** It is very confusing.  After PIR,  the output of the guest's SIR is the data in `breast_hetero_guest`(the input of the host). **That seems that the guest gets his own data(breast_hetero_guest) after SIR** .  In the setting of the SIR, **the guest wants to retrieve the host's data**. So it is more reasonable if the output of the guest's SIR is the host's data(breast_hetero_host). Please see pic following: 

image

image


In the above two pics, the output of the guest's SIR is the same as the breast_hetero_guest. This means that the guest finally gets his own data, instead of the host's data.

The logic of the SIR's code is correct. I still think it would be more reasonable to switch the input of the reader_0.

Nevertheless, since the SIR is experimental, whether switching the reader_0 or not does not matter. I just confuse about the conf setting. Would you be kindly solving my questions? Thanks anyway, and looking for your reply. :) 

@nemirorox @mgqa34

**Comment by nemirorox** [comment]
> 



> > Hi, this config file is to demonstrate server(guest) securely retrieves value from client(host). Use of datasets do not have to be restricted here as for other modules. Here we keep the choice of data sets consistent with the [earliest version](https://github.com/FederatedAI/FATE/blob/v1.5.0/examples/dsl/v1/secure_information_retrieval/test_secure_information_retrieval_conf.json). Therefore, we will not merge this PR as the current example works.
> 
> Hi, thanks for your reply! I still have questions.
> 
> I know it is the guest who wants to retrieve data from the host. But, In the original conf file, the `reader_0` of the guest is set to `breast_hetero_host`. **This means that the guest's input is the host's data.** It is very confusing. After PIR, the output of the guest's SIR is the data in `breast_hetero_guest`(the input of the host). **That seems that the guest gets his own data(breast_hetero_guest) after SIR** . In the setting of the SIR, **the guest wants to retrieve the host's data**. So it is more reasonable if the output of the guest's SIR is the host's data(breast_hetero_host). Please see pic following:
> 
> image
> 
> image
> 
> In the above two pics, the output of the guest's SIR is the same as the breast_hetero_guest. This means that the guest finally gets his own data, instead of the host's data.
> 
> The logic of the SIR's code is correct. I still think it would be more reasonable to switch the input of the reader_0.
> 
> Nevertheless, since the SIR is experimental, whether switching the reader_0 or not does not matter. I just confuse about the conf setting. Would you be kindly solving my questions? Thanks anyway, and looking for your reply. :)
> 
> @nemirorox @mgqa34

Hi, naming rules of example data sets can be referred [here](https://github.com/FederatedAI/FATE/tree/master/examples/data#data-set-naming-rule). We designed naming and division of example data sets to reflect their use in Hetero/Homo scenario. Inclusion of words 'host' or 'guest' do not necessarily bonds specific data sets to corresponding roles. As an example, if we switch host's and guest's data sets in some Homo LR example, new job will run just fine.  

On the other hand, SIR as a module is not restricted to either mode. Like some other modules such as Hetero Pearson, guest(as a role defined in FATE) may use breast_hetero_host as its input data,  and host breast_hetero_guest, the job will still run smoothly (maybe with some edits to configuration for DataTransform in current example). 

Hope this helps clarify any remaining confusion.

**Comment by gxcuit** [comment]
> > 
> 
> > > Hi, this config file is to demonstrate server(guest) securely retrieves value from client(host). Use of datasets do not have to be restricted here as for other modules. Here we keep the choice of data sets consistent with the [earliest version](https://github.com/FederatedAI/FATE/blob/v1.5.0/examples/dsl/v1/secure_information_retrieval/test_secure_information_retrieval_conf.json). Therefore, we will not merge this PR as the current example works.
> > 
> > 
> > Hi, thanks for your reply! I still have questions.
> > I know it is the guest who wants to retrieve data from the host. But, In the original conf file, the `reader_0` of the guest is set to `breast_hetero_host`. **This means that the guest's input is the host's data.** It is very confusing. After PIR, the output of the guest's SIR is the data in `breast_hetero_guest`(the input of the host). **That seems that the guest gets his own data(breast_hetero_guest) after SIR** . In the setting of the SIR, **the guest wants to retrieve the host's data**. So it is more reasonable if the output of the guest's SIR is the host's data(breast_hetero_host). Please see pic following:
> > image
> > image
> > In the above two pics, the output of the guest's SIR is the same as the breast_hetero_guest. This means that the guest finally gets his own data, instead of the host's data.
> > The logic of the SIR's code is correct. I still think it would be more reasonable to switch the input of the reader_0.
> > Nevertheless, since the SIR is experimental, whether switching the reader_0 or not does not matter. I just confuse about the conf setting. Would you be kindly solving my questions? Thanks anyway, and looking for your reply. :)
> > @nemirorox @mgqa34
> 
> Hi, naming rules of example data sets can be referred [here](https://github.com/FederatedAI/FATE/tree/master/examples/data#data-set-naming-rule). We designed naming and division of example data sets to reflect their use in Hetero/Homo scenario. Inclusion of words 'host' or 'guest' do not necessarily bonds specific data sets to corresponding roles. As an example, if we switch host's and guest's data sets in some Homo LR example, new job will run just fine.
> 
> On the other hand, SIR as a module is not restricted to either mode. Like some other modules such as Hetero Pearson, guest(as a role defined in FATE) may use breast_hetero_host as its input data, and host breast_hetero_guest, the job will still run smoothly (maybe with some edits to configuration for DataTransform in current example).
> 
> Hope this helps clarify any remaining confusion.

Thanks for your reply, even if I still think switching would be better. :)  
Never mind, developers could change the conf file anyway.

Once again, thanks a lot for your answer. I will close this PR.

**Pull request closed without merging**
