### PR TITLE
perf(data_split): change filter function to join

### PR DESCRIPTION
**Pull request by hust-suwb**
Changes:

1. Change filter function to join function in data_split component.

By changing filter to join function, data_split component running time can be extremely optimized. For example, when dealing with a dataset with 3,000,000 elements, the cost decrease from 20,000 seconds to almost 200 seconds in my environment.

### CODE REVIEW

**Comment by nemirorox** [comment]
Hello, thank you for your pull request. Do you mind giving us details on the test env(cores, memory etc.) and job conf? We would like to test the proposed improvement.

**Comment by hust-suwb** [comment]
- job conf：job conf
- filter function log：filter function log
- map+join function log：map+join function log

@nemirorox 
Hello, I use eggroll as storage and computing engine, each participants(one guest and one host) has one server with 42 cores and 168GB memory. As the above screenshot says, the data_split component takes 21271s vs 259s under one same dataset(3,000,000+ rows, 40 features together).

**Comment by nemirorox** [comment]
Hello, we have set up a new contributor branch for this pr. Please redirect your pr to 'contributor-1.6.1-data-split-join'; our team can then work from there to merge this update into developing branch. Thank you!

**Comment by hust-suwb** [comment]
I checkout this branch based on master, and branch 'contributor-1.6.1-data-split-join' is behind master. Do you mean close this pr and checkout a new branch based on 'contributor-1.6.1-data-split-join'?

**Comment by nemirorox** [comment]
> I checkout this branch based on master, and branch 'contributor-1.6.1-data-split-join' is behind master. Do you mean close this pr and checkout a new branch based on 'contributor-1.6.1-data-split-join'?

Yes, that would be the safest route.

**Comment by hust-suwb** [comment]
> > I checkout this branch based on master, and branch 'contributor-1.6.1-data-split-join' is behind master. Do you mean close this pr and checkout a new branch based on 'contributor-1.6.1-data-split-join'?
> 
> Yes, that would be the safest route.

#2957 
done

**Pull request closed without merging**
