### PR TITLE
conf_utils optimization

### PR DESCRIPTION
**Pull request by MiKKiYang**
@zhihuiwan 

修改文件：
python/fate_arch/common/conf_utils.py

修改内容：
增强get_base_config函数能力，支持一次查询service_conf.conf文件所有配置内容

### CODE REVIEW

**Review by dylan-fan — APPROVED** [review]
def get_base_config(key=None, default=None, conf_name=SERVICE_CONF) -> dict:
    local_path = conf_realpath(f'local.{conf_name}')
    if os.path.exists(local_path):
        local_config = file_utils.load_yaml_conf(local_path)
        if isinstance(local_config, dict):
            if key is None:
                return local_config
            if key in local_config:
                return local_config[key]

    config = file_utils.load_yaml_conf(conf_realpath(conf_name))
    if isinstance(config, dict):
        if key is None:
            return config
        return config.get(key, default)

**Comment by dylan-fan** [comment]
To keep the design consistent，when key is None ,  then get all of configs. This may be better.

**Review by dylan-fan — COMMENTED** [review]
use "key is None"

**Comment by MiKKiYang** [comment]
@dylan-fan hi、dylan，tks for ur suggests，i hv fix my code , but im not clear why this check is failed by the details，can you give some suggests?

**Review by dylan-fan — APPROVED** [review]

**Pull request merged**
