### PR TITLE
Fix example doc

### PR DESCRIPTION
**Pull request by MissiontoMars**
Signed-off-by: githubID email

Fixes  ISSUE #xxx

Changes:

1.

2.

3.

### CODE REVIEW

**Comment by MissiontoMars** [comment]
@nemirorox @dylan-fan

**Comment by weiwee** [comment]
Thanks report! please fix DCO according this  https://github.com/FederatedAI/FATE/pull/3577/checks?check_run_id=4655573209

**Comment by MissiontoMars** [comment]
> Thanks report! Please fix DCO according this https://github.com/FederatedAI/FATE/pull/3577/checks?check_run_id=4655573209 @MissiontoMars

Done.

**Review by weiwee — APPROVED** [review]

**Comment by MissiontoMars** [comment]
Could we merge this PR? @mgqa34 @dylan-fan

**Review by dylan-fan — APPROVED** [review]

**Pull request merged**
