### PR TITLE
change the code implementation for alignment in homo_ohe_arbiter.py t…

### PR DESCRIPTION
**Pull request by SennriSyunnga**
…o a more efficient way since that creating sets and lists frequently causes great cost.

Signed-off-by: SennriSyunnga nnnnnn_2657@qq.com

Fixes  ISSUE #3951

Changes:

1. Since creating sets and lists repeatedly leads to abundant performance cost, this code shifts the implementation for aligning headers to a more efficient way.

2.

3.

### CODE REVIEW

**Comment by SennriSyunnga** [comment]
I found that I mistook `add` for `update`. So I fixed it just now.
Hope that it didn't cause any problem...
BTW, I notice that  `read the docs build failed` still exists. Is it my problem?

**Comment by mgqa34** [comment]
> I found that I mistook `add` for `update`. So I fixed it just now. Hope that it didn't cause any problem... BTW, I notice that `read the docs build failed` still exists. Is it my problem?
Ignore this error


> I found that I mistook `add` for `update`. So I fixed it just now. Hope that it didn't cause any problem... BTW, I notice that `read the docs build failed` still exists. Is it my problem?

Your 

> I found that I mistook `add` for `update`. So I fixed it just now. Hope that it didn't cause any problem... BTW, I notice that `read the docs build failed` still exists. Is it my problem?

This can be ignored, it will be fixed later.

**Comment by mgqa34** [comment]
> > I found that I mistook `add` for `update`. So I fixed it just now. Hope that it didn't cause any problem... BTW, I notice that `read the docs build failed` still exists. Is it my problem?
> 
> This can be ignored, it will be fixed later.

**Comment by mgqa34** [comment]
I change this pr to develop-1.9, it will be test with fate-v1.9

**Review by mgqa34 — APPROVED** [review]

**Pull request merged**
